### ISSUE TITLE
how its works ?

### ISSUE THREAD

**Issue by vhgarcia** [raitono/LoLPA#1]

**Comment by raitono** [comment]
Check out Mobalytics if you want something similar that is actually complete. This is just a repository for me to hold a personal project and is not intended to ever be released to the public. If I could make it private, I would but you have to pay for that.

**Comment by vhgarcia** [comment]
Sorry for the question, I'm new to this part of programming. I'm learning typescript and wanted to see how your project worked out of curiosity.

Could you teach me how to install this project? Sorry again.

**Comment by raitono** [comment]
I appreciate you looking for ways to learn, but this project is not the place to do that. I'm a beginner too and also trying to learn. This is my first project using these. It is an Angular 4 based website using Node.js and MySQL for the backend.

I used the Angular 4 CLI to generate the majority of what is in the app folder. I would suggest looking at the documentation for it because it makes setting up a sample project very easy. Here is a link: https://cli.angular.io/

If you're serious about learning, there is a good course on Udemy that you can watch. You do have to pay for it, but don't be fooled by the large price tags. That is a marketing gimmick. All their courses are about $10 and this one has hours of video to watch covering pretty much all of Angular. Link: https://www.udemy.com/the-complete-guide-to-angular-2/learn/v4/overview

Other technologies I am working with here are Node.js, Express.js, and MySQL.

Here is another Angular 4 video I found, this time on Youtube so it is free to watch. It is an hour long. https://www.youtube.com/watch?v=KhzGSHNhnbI

I hope you find what you're looking for, but this project probably won't teach you much since I don't know much myself. I really recommend looking somewhere else if you're trying to learn.

**Comment by vhgarcia** [comment]
ty for your tips
